### ISSUE TITLE
requestedAuthnContext should default to False

### ISSUE THREAD

**Issue by todds02** [SAML-Toolkits/python3-saml#104]
The onelogin/php-saml library had an issue reported that we're running into on the python version:

https://github.com/onelogin/php-saml/issues/62

php-saml was modified to have requestAuthnContext default to False.  Should the same fix (and configuration advice) be made to python3-saml as well?

**Comment by pitbulk** [comment]
Do you have a PR?

**Comment by usmanakramb** [comment]
@pitbulk submitted related #227
