### ISSUE TITLE
URL validator should allow single label hostnames (those without a dot)

### ISSUE THREAD

**Issue by jgehrcke** [SAML-Toolkits/python3-saml#108]
python3-saml [implements](https://github.com/onelogin/python3-saml/blob/db1e9a6417511a49fdae42c44a3a386267d8bb16/src/onelogin/saml2/settings.py#L45 ) a URL validator, for e.g. the SSO or the SLO URLs provides in the IdP/SP settings dictionary. 

This URL passes validation: `'https://localhost:8088/sso/redirect'`
This one does not: `'https://somehost:8088/sso/redirect'`

`localhost` is treated special, and as of now the only single label hostname that is allowed. I believe that this is too strict because not only in testing environments it is common to use single label hostnames, but also in some smaller company environments I think it is a fair scenario to have an IdP deployed at e.g. `https://identity-service:1337/sso`.

For example, this passes the current validator: `'https://somehost.foo:8088/sso/redirect'`

I think the current strictness does not add to security, but can make some deployments harder than necessary.

From https://tools.ietf.org/html/rfc3986#section-3.2.2 (the current RFC specifying URI/Ls):
```
   A host identified by a registered name is a sequence of characters
   usually intended for lookup within a locally defined host or service
   name registry, though the URI's scheme-specific semantics may require
   that a specific registry (or fixed name table) be used instead.
[...]
   This specification does not mandate a particular registered name
   lookup technology and therefore does not restrict the syntax of reg-
   name beyond what is necessary for interoperability.  Instead, it
   delegates the issue of registered name syntax conformance to the
   operating system of each application performing URI resolution, and
   that operating system decides what it will allow for the purpose of
   host identification.  A URI resolution implementation might use DNS,
   host tables, yellow pages, NetInfo, WINS, or any other system for
   lookup of registered names.  However, a globally scoped naming
   system, such as DNS fully qualified domain names, is necessary for
   URIs intended to have global scope.  URI producers should use names
   that conform to the DNS syntax, even when use of DNS is not
   immediately apparent, and should limit these names to no more than
   255 characters in length.
```

I find "This specification does not mandate a particular registered name lookup technology and therefore does not restrict the syntax of reg-name beyond what is necessary for interoperability" particularly convincing. 

Related discussions elsewhere:
- https://github.com/jquery-validation/jquery-validation/issues/787
- https://github.com/onelogin/python3-saml/pull/54
- https://github.com/onelogin/php-saml/pull/207
- https://support.microsoft.com/en-us/help/2269810/microsoft-support-for-single-label-domains

**Comment by jgehrcke** [comment]
We have monkey-patched the validator in our code base:
```
# Monkey-patch python3-saml's URL validator to relax hostname validation
onelogin.saml2.settings.validate_url = _custom_sp_url_validator
```

**Comment by pitbulk** [comment]
Can you provide your _custom_sp_url_validator so I can analyze?

**Comment by jgehrcke** [comment]
> Can you provide your _custom_sp_url_validator so I can analyze?

Thank you for asking :) Hope you are great, long time no interaction.

In our case we use a really ignorant one which basically does not do any DNS name validation at all. I am not sure if that is really what we want here for all users of the library. Some users might rely on the DNS name length validation, for example. Right?

I think if I were to write a patch for the library (which I might do) I would replace the explicit check for `localhost` in the regex with a more generic check. What do you think?

**Comment by nlfiedler** [comment]
This is especially relevant to Docker, in which containers often have short names and Docker Compose automatically configures the containers to resolve using those short names. Otherwise I have to name my containers in domain name form, which is just silly.

**Comment by shaleh** [comment]
What is wrong with using `urlparse` as a starting point?

```
>>> from urllib.parse import urlparse
>>> urlparse('http://application/a/b/c/?acs')
ParseResult(scheme='http', netloc='application', path='/a/b/c/', params='', query='acs', fragment='')
```

You can validate the scheme easily. urlparse will also tell you if the url is totally wrong.

```
>>> urlparse('http:application/a/b/c/?acs')
ParseResult(scheme='http', netloc='', path='application/a/b/c/', params='', query='acs', fragment='')
```

Here, a netloc is not empty check would work.

```
>>> urlparse('http:///application/a/b/c/?acs')
ParseResult(scheme='http', netloc='', path='/application/a/b/c/', params='', query='acs', fragment='')
```
Here too.

**Comment by shaleh** [comment]
locally i have done what @jgehrcke suggested and added `r'(?:\w+)|` before `localhost` in the url_regex.

**Comment by flyte** [comment]
We've just hit this on docker/kubernetes. I tend to disagree that this is an 'enhancement' request, since the validation breaks the library for our valid use cases.

Any word on when this is likely to be worked on?

**Comment by pitbulk** [comment]
Implemented at https://github.com/SAML-Toolkits/python3-saml/commit/a1e1f8b4d0fa4cd17467446f5cbe72dc1fc80bd8
