### ISSUE TITLE
Conditions element not found

### ISSUE THREAD

**Issue by busla** [SAML-Toolkits/python3-saml#109]
`The Assertion must include a Conditions element` exception is being raised on the following xml.

The `final_query` returned from https://github.com/onelogin/python3-saml/blob/4460fb97cc13ca9e699765893f3ff123d883c499/src/onelogin/saml2/response.py#L729 is `/samlp:Response[@ID='']//saml:Assertion/saml:Conditions`.

Looks like the `ID` is not being passed when parsed.

```xml
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsd="http://www.w3.org/2001/XMLSchema" ID="removed" Version="2.0" IssueInstant="2018-08-24T18:06:44.9968865Z" Destination="removed">
    <saml:Issuer>removed</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
            <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
            <ds:Reference URI="">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                <ds:DigestValue>removed</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>removed</ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>removed</ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></samlp:Status>
    <saml:Assertion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="2.0" ID="removed" IssueInstant="2018-08-24T18:06:44.9968865Z">
        <saml:Issuer>removed</saml:Issuer>
        <saml:Subject>
            <saml:NameID NameQualifier="removed" />
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData Address="10.121.57.25" NotOnOrAfter="2018-08-24T18:11:44.9968865Z" Recipient="removed" /></saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2018-08-24T18:06:34.9968865Z" NotOnOrAfter="2018-08-24T18:11:44.9968865Z">
            <saml:AudienceRestriction>
                <saml:Audience>removed</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2018-08-24T18:06:44.9968865Z">
            <saml:SubjectLocality Address="212.30.225.139" />
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:TLSClient</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="UserSSN" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" FriendlyName="User ssn">
                <saml:AttributeValue xsi:type="xsd:string">removed</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>
```

**Comment by busla** [comment]
Thanks for putting time into this :+1:
The IDP is the Iceland National Registry, I would have to investigate what software they are using.

Note that the above saml2 is a modified response from the IDP, original response can be seen in #107.

**Comment by deceze** [comment]
I'm seeing the same problem with the response from [LINE WORKS](https://developers.worksmobile.com/jp/document/1001500302?lang=en):

```xml
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="http://localhost:5000/?acs" ID="redacted" InResponseTo="ONELOGIN_redacted" IssueInstant="2020-11-26T08:27:29.147Z" Version="2.0">
  <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://auth.worksmobile.com/saml2/works-redacted</saml2:Issuer>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/>
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <DigestValue>redacted</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>redacted</SignatureValue>
    <KeyInfo>
      <X509Data>
        <X509Certificate>redacted</X509Certificate>
      </X509Data>
    </KeyInfo>
  </Signature>
  <saml2p:Status>
    <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
  </saml2p:Status>
  <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="redacted" IssueInstant="2020-11-26T08:27:29.147Z" Version="2.0">
    <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://auth.worksmobile.com/saml2/works-redacted</saml2:Issuer>
    <saml2:Subject>
      <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">redacted</saml2:NameID>
      <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml2:SubjectConfirmationData InResponseTo="ONELOGIN_redacted" NotOnOrAfter="2022-11-26T08:27:29.147Z" Recipient="http://localhost:5000/?acs"/>
      </saml2:SubjectConfirmation>
    </saml2:Subject>
    <saml2:Conditions NotBefore="2020-11-26T08:27:29.147Z" NotOnOrAfter="2022-11-26T08:27:29.147Z">
      <saml2:AudienceRestriction>
        <saml2:Audience>http://localhost:5000/metadata</saml2:Audience>
      </saml2:AudienceRestriction>
    </saml2:Conditions>
    <saml2:AuthnStatement AuthnInstant="2020-11-26T08:27:29.147Z" SessionIndex="redacted">
      <saml2:AuthnContext>
        <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml2:AuthnContextClassRef>
      </saml2:AuthnContext>
    </saml2:AuthnStatement>
  </saml2:Assertion>
</saml2p:Response>
```

It's not a terribly thrilling idea to have to monkey-patch the library so it can handle this; would be nice if it could treat these responses out of the box.

**Comment by busla** [comment]
I think it's a matter of compliance with the Saml2 standard.

**Comment by busla** [comment]
_deleted a comment earlier, accidently posted an unfinished response._

**Comment by pitbulk** [comment]
Does the provided code fix the issue?
I will review if the patch has security implications and if not, apply it to the toolkit.

**Comment by deceze** [comment]
@pitbulk Yes, the above patch fixes the problem. I'm currently applying it with some ugly monkey patching at runtime. I have no idea whether the change has any other implications on functionality or standards compliance, but it "makes immediate the problem go away."

**Comment by busla** [comment]
Here is my observation about the topic.
* In the specs the attribute is optional [ref](https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd#enveloped-signature)
* `python3-saml` treats this as [required](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/response.py#L77)
* The `python3-saml` README does not state clearly that the library is _strictly compliant_ with the specs.

I ended up using [https://github.com/XML-Security/signxml](signxml) since they don't deviate from the specs. Here is how they treat the [Reference URI attribute](https://github.com/XML-Security/signxml/blob/develop/signxml/__init__.py#L228)

Is my IDP fully compliant? No, but in terms of `XMLDSig` they are, which is important.

My suggestion would be to either:
* Review the specs and refactor `python3-saml` validation where appropriate. There might be other issues.
* Update the README where it states that the library might not be compliant with the specs.

Please correct me if I am out of place here.

https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd#enveloped-signature
![2020-11-26_09-22](https://user-images.githubusercontent.com/3162968/100335071-748a8100-2fcc-11eb-8c84-d38a4cffe9dc.png)

**Comment by pitbulk** [comment]
We don't deviate from the standard intentionally, the standard is complex and we try to keep aligned. When a deviation is reported, we always try to fix it.

The SAML standard requires that the ID of the AuthNRequest must exist:
http://www.datypic.com/sc/saml2/e-samlp_AuthnRequest.html
which is the validation you [referenced here](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/response.py#L77)

I agree the ID of the Reference is optional

**Comment by busla** [comment]
No, ofcourse not. I hope this wasn't understood as an insult, that was not my intention.

As you point out correctly, the spec is complicated and this is a very ambitious library. Not to mention the effort that goes into making it open source and dealing with feature requests and bug reports.

And I should also have responded to your fix earlier.
