### ISSUE TITLE
OneLogin_Saml2_Response.is_valid() fails destination check behind application proxy

### ISSUE THREAD

**Issue by douglasbr** [SAML-Toolkits/python3-saml#134]
I have been using python3-saml in my Django application running on an internal network, and it has been working great. However, recently, our IT department decided to expose the application to the public internet through an application proxy as described [here](https://www.xtseminars.co.uk/blog/publishing-a-saml-app-through-the-azure-ad-application-proxy).

The result is that the ACS redirect to my application is proxied through the application proxy, which changes the host name of the ACS URL from the external host name (used in the Destination field of the XHTML form) to the internal host name (used by the proxy to talk to the application).

When OneLogin_Saml2_Auth.process_response() calls OneLogin_Saml2_Response.is_valid(), the Destination is checked against the current URL. Destination must be the public host name for the browser to reach my application through the proxy; but, the current URL will always be the internal host name because the proxy always uses that name when sending requests to the application. Therefore, the Destination check always fails, and returns an 'invalid_response' error with the error_reason, 'The response was received at %s instead of %s' % (current_url, destination).

I am hoping you can help me find the best way to overcome this problem. Some things I have considered...
1) Is there a SAML configuration that allows the destination check to pass, even when behind the application proxy?
2) Should I disable the destination check using a setting in the SAML settings JSON file?
3) Should I pass raise_exceptions=True through process_response() into response.is_valid(), then trap and ignore the OneLogin_Saml2_ValidationError.WRONG_DESTINATION error, since Django already validates that the request is coming to a URL with an 'allowed host'?
4) Is there a better option that I am missing?

I would really like to continue using the package distributed through pypi, so I am hoping that my use case is worth supporting.  But, I can pull the source into my application and make the change, if a change is required.

Thanks!

**Comment by douglasbr** [comment]
Some further information:
Getting past the Destination check, an error is thrown at the SubjectConfirmation check. In the SubjectConfirmation check, the current URL is also checked against the Recipient in the SubjectConfirmation.

**Comment by pitbulk** [comment]
At the [prepare_flask_request](https://github.com/onelogin/python3-saml/blob/master/demo-flask/index.py#L22) method you set values for https, http_host, server_port and script_name.

Those values are used later to generate the current_url value by the [get_self_url_no_query](https://github.com/onelogin/python3-saml/blob/29e1b51c1d830e1dd4c08455fcdb268d20bf7f36/src/onelogin/saml2/utils.py#L315) method
```
current_url = OneLogin_Saml2_Utils.get_self_url_no_query(request_data)
```

So all you need to do is to set the properly values at the prepare_flask_request to match the values of the SAMLResponse
