### ISSUE TITLE
DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.

### ISSUE THREAD

**Issue by j-walker23** [SAML-Toolkits/python3-saml#159]
Hello,

I am reviving some unit tests on unfamilar code and this is one warning that is popping up.
I don't know saml or defusedxml, so I don't have anything to add.

But I didn't see anything about it in the issues so I thought I'd add it.

Thanks for the lib!

**Comment by pitbulk** [comment]
Noted but we are not porting to a new xml parser library right now.

**Comment by j-walker23** [comment]
Makes sense, thanks!

**Comment by shaib** [comment]
It seems like the only uses in the code which trigger the warning are
```
saml2/xml_utils.py
14:from defusedxml.lxml import tostring, fromstring

saml2/auth.py
15:from defusedxml.lxml import tostring
```
I have yet to test this properly, but it seems like `fromstring` and `tostring` can be more-or-less equivalently be imported from `defusedxml.cElementTree`.

**Comment by pitbulk** [comment]
cElementTree was removed in Python 3.9. See tiran/defusedxml#50

**Comment by andersk** [comment]
That’s not relevant to this issue. `cElementTree` has been a deprecated alias of `ElementTree` [since Python 3.1](https://github.com/python/cpython/commit/a72a98f24a19928e31dcc4cab2cd2ad0f1846e11#diff-039d2c17bba26fba8a9eeb457251fed43d412b673360333f2a51ecf4a93aef4f), and only the alias was removed. `ElementTree` is still there.

**Comment by pitbulk** [comment]
Noted.

porting from
```
from defusedxml.lxml import fromstring, tostring
```
to
```
from defusedxml.ElementTree import fromstring, tostring
```

isn't trivial.

ElementTree uses find/findall instead xpath. Its syntax for the match parameter differ a bit and the [xpath support](https://docs.python.org/3/library/xml.etree.elementtree.html#xpath-support) for ElementTree is limited
