### ISSUE TITLE
Retrieving response from WS federation

### ISSUE THREAD

**Issue by vinothkumar1097** [SAML-Toolkits/python3-saml#183]
Hi Pitbulk,

I've done the same what you instructed. But after my page successfully authenticated via my web.config(ws federation), the page is throwing error.

**Error message**
 auth.process_response(request_id=None)
  File "D:\A697643\PythonApp\venv\lib\site-packages\onelogin\saml2\auth.py", line 135, in process_response  OneLogin_Saml2_Error.SAML_RESPONSE_NOT_FOUND
onelogin.saml2.errors.OneLogin_Saml2_Error: SAML Response not found, Only supported HTTP_POST Binding

![ws federation response](https://user-images.githubusercontent.com/35162372/74456073-49ef9180-4eac-11ea-8701-d2f97670bfe9.png)

###  ws federation authentication is successfull at this point and response can be seen as shown above. Once it enter into the route url, the page is not getting loaded and showing above error.

**Complete code**
def prepare_from_request(request):
    url_data = urlparse(request.url)
    return {
        'https': 'on' if request.scheme == 'https' else 'off',
        'http_host': request.host,
        'server_port': url_data.port,
        'script_name': request.path,
        'get_data': request.args.copy(),
        'post_data': request.form.copy(),
        'query_string': request.query_string
    }

def init_saml_auth(req):
    auth = OneLogin_Saml2_Auth(req, custom_base_path=app.config['SAML_PATH'])
    return auth

@app.route('/', methods=['GET','POST'])
def home():
    req = prepare_from_request(request)
    auth = init_saml_auth(req)
    request_id = None
    auth.process_response(request_id=None)
    errors = auth.get_errors()
    if len(errors) == 0:
        return auth.get_attributes().items()
    elif auth.get_settings().is_debug_active():
        error_reason = auth.get_last_error_reason()
        return 'Error {0}'.format(error_reason)

Am i doing anything wrong Pitbulk. pls assist me.

_Originally posted by @vinothkumar1097 in https://github.com/onelogin/onelogin-python-sdk/issues/38#issuecomment-585850703_

**Comment by pitbulk** [comment]
```
process_response OneLogin_Saml2_Error.SAML_RESPONSE_NOT_FOUND
```
Means that the toolkit was not able to read the SAMLResponse, the toolkit reads it from 
$_POST['SAMLResponse']

**Comment by vinothkumar1097** [comment]
so as you said, how can i implement **$_POST['SAMLResponse']** in my @app.route directly.

**OneLogin_Saml2_Auth class-- line 105**
response = OneLogin_Saml2_Response(self.__settings, self.__request_data['post_data']['SAMLResponse'])

To initialize above OneLogin_Saml2_Response class, we need to pass Settings and Response parameters. In above screenshot, you can see WS Federation response stored in my browser.
How can i retrieve its attributes directly using Response class ?
