### ISSUE TITLE
cant download libxml2 for windows 10

### ISSUE THREAD

**Issue by ronica4** [SAML-Toolkits/python3-saml#186]
i know there are similar questions but i tried everything and nothing seems to work...
i cant download python3-saml without xmlsec, and cant download xmlsec without libxml2
for example after donwloading the file manually (libxml2-2.9.4.tar) and pip installing it i get the error :
(venv) C:\Users\user\PycharmProjects\onelogintest>pip install libxml2-2.9.4.tar.gz
Processing c:\users\user\pycharmprojects\onelogintest\libxml2-2.9.4.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\tokenize.py", line 392, in open
buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\user\AppData\Local\Temp\pip-req-build-veuc4n_9\setup.py'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-req-build-veuc4n_9\

please help im really stuck

**Comment by pitbulk** [comment]
I found: https://www.lfd.uci.edu/~gohlke/pythonlibs/#libxml-python
can this help?

**Comment by hoefling** [comment]
A new version 1.3.7 of `xmlsec` [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.

**Comment by joesafe** [comment]
> A new version 1.3.7 of `xmlsec` [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:
> 
> 
> 
> ```sh
> 
> pip install xmlsec
> 
> ```
> 
> 
> 
> Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.

Can confirm the newer release of this fixed on Windows 10/newer server versions.
