### ISSUE TITLE
How to get in_response_to from SAML response

### ISSUE THREAD

**Issue by PaulStryck** [SAML-Toolkits/python3-saml#187]
Hi,
I couldn't find a simple way to get the in_response_to value from a Saml response when processing it with the Saml2_Auth object.

Only way I figured was `get_last_request()` on the Saml2_Auth object. But this returns the whole xml and would need parsing again. And I don't like the idea of parsing the xml twice just for a single attribute. 

Would it make sense to introduce an in_response_to property to the Saml2_Auth Class? Alternatively the last_request_id variable could be used like this in the `process_response()` method.
`self.__last_request_id = response.get_in_response_to()`

The latter makes some sense, as the in_response_to value should be the last request id.

**Comment by doticatto** [comment]
This already exists and was added in this MR

https://github.com/onelogin/python3-saml/pull/144

**Comment by PaulStryck** [comment]
Please correct me if I'm wrong, but #144 adds this to the response and logout_response classes only. So the Saml2_Auth class doesn't expose it.

When implementing the ACS like this:
```
req = prepare_request_for_toolkit(request)
auth = OneLogin_Saml2_Auth(req)
auth.process_response()
```
The best way to get the in_response_to attribute would be this:
```
xml = auth.get_last_response()
```
And then query the xml again.

I thought it might be a good idea to make the in_response_to field available from the Auth class.

**Comment by pitbulk** [comment]
Why do you need the in_response_to value?

There is a way to retrieve ID from the AuthNRequest and then use it on the SAMLResponse validation.
