### ISSUE TITLE
how should merge_settings() be used?

### ISSUE THREAD

**Issue by dgkatz** [SAML-Toolkits/python3-saml#188]
I would like to construct a settings object from custom base path (which will have files specifying sp configurations), then I would like to use the idp_metadata_parser to retreive and parse idp metadata via parse_remote() function.

I dont understand how to append/ammend a settings object with newly created idp metdata (via parse_remote()).

I see a merge_settings() function but it only accepts a dictionary to merge into, so i cant merge in new idp metadata into my existing settings object (of type OneLogin_Saml2_Settings).

Please advice, thankyou.

**Comment by pitbulk** [comment]
The merge_settings will update the settings dict (read the content of the settings file) with the provided new settings data extracted from the IdP metadata.

All you need to do is to read the dict from the settings, merge the new data extracted from the IdP Metadata, and then store the dict to have a new settings file or simply use the new dict to build the OneLogin_Saml2_Settings object.

**Comment by FISHMANPET** [comment]
How do you get the settings as a dict?  I see ways to get specific nodes (sp, idp, organization, etc) but no way to get the entire thing as a dict, do we need to get all 5 components individually and manually assemble a single dict of everything?
