### ISSUE TITLE
Access NameID from OneLogin_Saml2_Logout_Request

### ISSUE THREAD

**Issue by dgkatz** [SAML-Toolkits/python3-saml#189]
When i handle a slo request from IDP, i need to know which user needs to be logged out -- NameID. Is this possible?

Please advice.

**Comment by pitbulk** [comment]
With the process_slo method, the LogoutRequest is validated and then you can decide to kill the session associated with the browser, but you can as well keep_local_session=True and then use the 
[get_nameid_data](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/logout_request.py#L161) to retrieve the NameId Info.
