### ISSUE TITLE
Openssl 1.0 Deprecate Issue.

### ISSUE THREAD

**Issue by DavidAtWorking** [SAML-Toolkits/python3-saml#191]
Hi,

It seems homebrew have remove openssl 1.0.0 and I found you library is using xmlsec which refer to openssl 1.0.0

>   File "/usr/local/lib/python3.7/site-packages/onelogin/saml2/auth.py", line 14, in <module>
    import xmlsec
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/xmlsec.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/xmlsec.cpython-37m-darwin.so
  Reason: image not found

**Comment by darakian** [comment]
@DavidAtWorking A short term solution is to use the `1.0.2` branch.  Ex. ` brew switch openssl 1.0.2t`

**Comment by hoefling** [comment]
@darakian @DavidAtWorking do you still experience this issue with the latest release of `xmlsec`? Trying to reproduce it on 10.15.4. This is what I have installed via Homebrew:

```sh
 % brew info openssl
openssl@1.1: stable 1.1.1g (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1g (8,059 files, 18MB)
  Poured from bottle on 2020-05-19 at 22:09:22
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl@1.1.rb
...
 % brew info libxml2
libxml2: stable 2.9.10 (bottled), HEAD [keg-only]
GNOME XML library
http://xmlsoft.org/
/usr/local/Cellar/libxml2/2.9.10_1 (280 files, 10.5MB)
  Poured from bottle on 2020-05-22 at 00:20:24
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libxml2.rb
...
 % brew info libxmlsec1
libxmlsec1: stable 1.2.30 (bottled)
XML security library
https://www.aleksey.com/xmlsec/
/usr/local/Cellar/libxmlsec1/1.2.30 (220 files, 5.6MB) *
  Poured from bottle on 2020-05-22 at 00:20:34
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libxmlsec1.rb
...
 % brew info pkg-config
pkg-config: stable 0.29.2 (bottled)
Manage compile and link flags for libraries
https://freedesktop.org/wiki/Software/pkg-config/
/usr/local/Cellar/pkg-config/0.29.2_3 (11 files, 623.7KB) *
  Poured from bottle on 2020-05-22 at 00:20:38
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pkg-config.rb
```

Installing `xmlsec`:

```sh
$ python3 -V
Python 3.6.8
$ python3 -m venv test
$ source test/bin/activate
(test) $ pip install xmlsec
...
Successfully installed lxml-4.5.1 xmlsec-1.3.8
(test) $ otool -L test/lib/python3.6/site-packages/xmlsec.cpython-36m-darwin.so
test/lib/python3.6/site-packages/xmlsec.cpython-36m-darwin.so:
	/usr/local/opt/libxmlsec1/lib/libxmlsec1-openssl.1.dylib (compatibility version 4.0.0, current version 4.30.0)
	/usr/local/opt/libxmlsec1/lib/libxmlsec1.1.dylib (compatibility version 4.0.0, current version 4.30.0)
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 64.2.0)
```

**Comment by darakian** [comment]
@hoefling All is working well in my project
I've updated lxml to 4.5.1 which pulls xmlsec 1.3.8 and everything works with openssl 1.1.1g

Many thanks :)

**Comment by darakian** [comment]
The update in my poetry lock file looks like
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/3607524/82615920-83592c80-9b80-11ea-80bb-07964c4bbe52.png">
There are more with the tar at the bottom. Not sure if that's on you or on lxml.

**Comment by hoefling** [comment]
@darakian 

> All is working well in my project

glad to hear that!

> all the wheels seem to be marked as windows wheel despite me not using windows OS.

This is as expected - `poetry` stores the hashes of all wheels as the lock file is not platform specific. The list of wheels is also correct - I haven't released any wheels except for windows yet. On Linux and MacOS, I'm not sure how to handle the OpenSSL dependency, I have described my reasoning [here](https://github.com/mehcode/python-xmlsec/issues/109#issuecomment-632157339).

**Comment by darakian** [comment]
> This is as expected - poetry stores the hashes of all wheels as the lock file is not platform specific. 

Makes sense. Thank you again for the work :)
