### ISSUE TITLE
saml with ADFS

### ISSUE THREAD

**Issue by ronica4** [SAML-Toolkits/python3-saml#195]
I've been trying to connect my sp with ADFS 5.0 as idp.
At first the ADFS didn't approve my sp metadata xml that I created using this code
req = prepare_request_for_toolkit(request)
auth = OneLogin_Saml2_Auth(req)
saml_settings = auth.get_settings()
metadata = saml_settings.get_sp_metadata()
errors = saml_settings.validate_metadata(metadata)
etc..., so I created my own metadata file based on other files that the adfs did accept, and it worked.
that is the file: 
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://myapp/metadata.xml">
<SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol">
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://myapp/?sls"/>
<NameIDFormat>
urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
</NameIDFormat>
<KeyInfo>
<x509Data>
<x509Certificate>certificate</x509Certificate>
</x509Data>
</KeyInfo>
<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://myapp/?acs" index="0"/>
<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://myapp/metadata.xml" index="1"/>
</SPSSODescriptor>
<ContactPerson contactType="technical">
<GivenName>Administrator</GivenName>
<EmailAddress>noreply@example.org</EmailAddress>
</ContactPerson>
</EntityDescriptor>

So now- my problem is that when I click login, I get directed to a page that wants me to provide my username and password, and what I want for my app is to know that I am already logged in in the first place, using my biometric fingerprint. Basically I want to already be identified as I enter my app, without needing the login button and so.
Does anyone know how to fix my problem and has a solution for this whole saml with ADFS things? thanks in advance :)

**Comment by ronica4** [comment]
that is the sp metadata- (I'm removing the tags so you can see it)
EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://myapp/metadata.xml"
SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol"
SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://myapp/?sls"/
NameIDFormat
urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
/NameIDFormat
KeyInfo
x509Data
x509Certificate>certificate</x509Certificate
/x509Data
/KeyInfo
AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://myapp/?acs" index="0"/
AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://myapp/metadata.xml" index="1"/
/SPSSODescriptor
ContactPerson contactType="technical"
GivenName>Administrator</GivenName
EmailAddress>noreply@example.org</EmailAddress
/ContactPerson
/EntityDescriptor

**Comment by ronica4** [comment]
UPDATE: I found a variable in python3-saml/src/onelogin/saml2/constants.py-
    AC_SMARTCARD = 'urn:oasis:names:tc:SAML:2.0:ac:classes:Smartcard'
seems to solve my problem, but I don't know how to add it to the setting/metadata or where?

**Comment by pitbulk** [comment]
In the settings file, add:
```
requestedAuthnContext = ["urn:oasis:names:tc:SAML:2.0:ac:classes:Smartcard"]
```

**Comment by ronica4** [comment]
where should i add it? @pitbulk

**Comment by ronica4** [comment]
also i have another problem, i get "invalid issuer in the assertion/response", what can i do?

**Comment by pitbulk** [comment]
At the setting file, for example:
https://github.com/onelogin/python3-saml/blob/master/demo-django/saml/advanced_settings.json
