### ISSUE TITLE
Support for Django 3?

### ISSUE THREAD

**Issue by fitzgeralddp** [SAML-Toolkits/python3-saml#196]
It appears that python3-saml doesn't support Django 3. Is that true? Are there plans to update?

**Comment by pitbulk** [comment]
There is no demo for Django3, but I don't see why python3-saml can't be used on Django3 apps.

**Comment by fitzgeralddp** [comment]
I actually went ahead and implemented this myself, and I will post the link to the repository when I get around to uploading it. There will be some delays, so I would expect within a month.

**Comment by adipon** [comment]
@fitzgeralddp Can you post a link to your repo that works with a django3 app? I have been trying to use the existing demo but have run into issues with acs.

**Comment by fitzgeralddp** [comment]
@adipon It was closed source, and I ended up not getting over the hurdles that would allow for my publicly releasing this part and am no longer in a position to do so, so unfortunately it's not going to happen. I'm sorry!
