### ISSUE TITLE
EVP_VerifyFinal: signature does not verify - behind NGINX ingress on Kubernetes

### ISSUE THREAD

**Issue by albertmichaelj** [SAML-Toolkits/python3-saml#206]
I am getting an error that I can't figure out, and I can't tell if it is a bug or a misconfiguration. I am using `python3-saml` in a tornado application running behind the standard kubernetes NGINX ingress on a kubernetes cluster on AWS (specifically on EKS). So, the NGINX ingress is itself behind a AWS ELB. I am using a self-signed certificate. Debug settings is `false`, and strict mode is `True`. I get the below xmlsec errors:

```
[D 2020-08-03 12:06:11.622 AuthHub handlers:121] Debug setting is: 'False'
[D 2020-08-03 12:06:11.622 AuthHub handlers:122] Strict mode is active: 'True'
func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=341:obj=x509-store:subj=unknown:error=71:certificate verification failed:X509_verify_cert: subject=/C=US/ST=****/L=****/O=***/OU=****/CN=****; issuer=/C=US/ST=****/L=****/O=***/OU=****/CN=****; err=18; msg=self signed certificate
func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=380:obj=x509-store:subj=unknown:error=71:certificate verification failed:subject=/C=US/ST=****/L=****/O=***/OU=****/CN=****; issuer=/C=US/ST=****/L=****/O=***/OU=****/CN=****; err=18; msg=self signed certificate
func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=364:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify
func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=364:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify
```

If I run my application without the NGINX ingress (i.e., directly behind the load balancer) with my self-signed certificate, then I do not get any `certificate verification failed` (unless I turn on debug mode) errors or `signature does not verify` (I do not get these even in debug mode). However, behind the NGINX ingress, I get both errors no matter what I set debug to. To be clear, authentication proceeds, so these errors do not stop authentication, but they clutter up the logs and make me think that somethin gis wrong.

I terminate SSL at the NGINX ingress, so I have to force `https` to `'on'`, which I do by constructing the request as below (gently modified from the example tornado application). Is there anything that I'm missing?

``` python
    def prepare_tornado_request(self, request):

        dataDict = {}
        for key in request.arguments:
            dataDict[key] = request.arguments[key][0].decode('utf-8')

        result = {
            'https': 'on' if request == 'https' else 'off',
            'http_host': split_host_and_port(request.host)[0],
            'script_name': request.path,
            'server_port': split_host_and_port(request.host)[1],
            'get_data': dataDict,
            'post_data': dataDict,
            'query_string': request.query
        }

        if self.force_https:
            result['https'] = self.force_https

        self.log.debug("The values used for the tornado request are: %r" % result)

        return result
```

**Comment by pitbulk** [comment]
Yes, when you are under a proxy you will need to make some tricks, like forcing some values when preparing the tornado request so destination validation will pass.

Are you sure that those errors came from the python3-saml module while validating the SAMLResponse?

**Comment by albertmichaelj** [comment]
I'm sure that those came from the `python3-saml` function call. I think it is actually from the `xmlsec` module that is actually raising that error, but it has something to do with how the `python3-saml` module is passing the request to `xmlsec`. I don't have a good understanding of `xmlsec`, so I'm at a loss of getting rid of the messages (though they don't seem to be harming anything I can tell other than cluttering up the logs).

Thoughts?
