### ISSUE TITLE
Allow setting request ID by hand?

### ISSUE THREAD

**Issue by akx** [SAML-Toolkits/python3-saml#208]
It would be useful to be able to optionally pass a request ID to `onelogin.saml2.auth.OneLogin_Saml2_Auth.login()` instead of the library forcibly generating <sub>a branded</sub> one via `onelogin.saml2.utils.OneLogin_Saml2_Utils.generate_unique_id()`.

Is there a good reason not to allow this?

**Comment by pitbulk** [comment]
What is the point of adding a new parameter to the login method adding complexity to it in order to be able to set an specific request id that at the end is never show to the end user?

Is is very important for you not generating a branded Request ID, you can always create your own version of the generate_unique_id method.

**Comment by pitbulk** [comment]
You can also extend the class and override the constructor.
Agree is not an ideal solution.

**Comment by akx** [comment]
Since the constructor also internally creates the XML message used for the request (why?!), that'd mean copy-pasting all 110 lines of the constructor, which I'm quite unwilling to do.

Allowing a `request_id=None` argument and doing something like `request_id = str(request_id or OneLogin...generate_unique_id())` would be the simplest solution in my eyes.

**Comment by pitbulk** [comment]
Im not adding a new parameter required in the 1% of cases.

As you pointed is hard to override the whole constructor.
What do you think if you add a new method:
set_id
that will contain:
```
uid = OneLogin_Saml2_Utils.generate_unique_id() 
```
and its used on constructor

Im happy to accept such PR and then for you the fact of be able to set an specific id gonna be as simple as override such new method.

**Comment by spaceone** [comment]
I would also like to see this feature implemented.
