### ISSUE TITLE
Make hardcoded certificate paths configurable

### ISSUE THREAD

**Issue by spaceone** [SAML-Toolkits/python3-saml#222]
It would be nice if the config could contain an absolute path to the certificate data.
Currently one must have a `sp.crt` and `sp.key` in the same directory.

The config just should allow to specify:
`sp.x509cert_path = '/foo/bar.pem`
`sp.privateKey_path = /foo/bar`

**Comment by pitbulk** [comment]
You have the 'custom_base_path' parameter to determine the path to store settings and certs.

And at https://github.com/onelogin/python3-saml/commit/6728e7f188b3639eb14f8584a00defae43a2d2f2 I just added a way to have a different path for the certs and the settings by the use of set_cert_path
