### ISSUE TITLE
Is it planned to provide Debian packages?

### ISSUE THREAD

**Issue by spaceone** [SAML-Toolkits/python3-saml#224]
Hello,

is it planned to provide Debian packages for this project?
At least I couldn't find any, while https://github.com/IdentityPython/pysaml2/ is part of Debian (https://packages.debian.org/buster/python3-pysaml2).

**Comment by pitbulk** [comment]
Debian packages are managed by Debian community. 
I guess you may ask at Debian community about include this tooklit as well.
