### ISSUE TITLE
[Question] - How to Identify / distinguish between a regular SAML 2.0 and AD FS SAML2.0

### ISSUE THREAD

**Issue by tomerbsentinel** [SAML-Toolkits/python3-saml#243]
From your docs, I can see this line:
lowercase_urlencoding - Defaults to false. ADFS users should set this to true.

The question is, is there a way to differentiate between customers that are using SAML 2.0 Azure ( for example ) and SAML 2.0 AD FS?

**Comment by pitbulk** [comment]
You only need to enable this, if you experience issues while validating the Signatures of the LogoutReqquest/LogoutResponses generated by ADFS. If you don't experience any issue, you don't need to enable it.

**Comment by tobenary** [comment]
Hi @pitbulk
Understood, the reason I am asking it is because I need both methods. 
Now adfs is not working (Azure adfs)
Can you please also check it on your end?
