### ISSUE TITLE
Missing Format and NameQualifier attribute in AUTHN_REQUEST template

### ISSUE THREAD

**Issue by zephir89** [SAML-Toolkits/python3-saml#25]
Hi!
I noticed it is not provided the possibility to add _NameQualifier_ and _Format_ attributes to the element _Issuer_ in the AUTHN_REQUEST template. It would be great if we could set them in the settings file, like others.
Thank you!

**Comment by salvorapi** [comment]
+1

**Comment by pitbulk** [comment]
The saml:Issuer element is an [optional](http://www.datypic.com/sc/saml2/e-samlp_AuthnRequest.html) parameter of an AUTHN_REQUEST.

NameQualifier, SPNameQualifier, Format and SPProvidedID  are also [optional](http://www.datypic.com/sc/saml2/e-saml_Issuer.html) attributes of the Issuer element.

Support that will turn the settings more complex and this is something that we want to avoid.

If your projet requires it, I recommend to extend the toolkit with a custom AuthNRequest class that support that.

**Comment by salvorapi** [comment]
Hi!

I have the same requirement of @zephir89. It's true that saml:Issuer element is an optional parameter but can be "requested" by custom IDP.
And if I choose to use this library with my django application can be helpful (and a great feature) to set this optional parameter on my SP settings.

Thank you.

Salvo.
