### ISSUE TITLE
ClockSkew configuration

### ISSUE THREAD

**Issue by franciscodelgadodp** [SAML-Toolkits/python3-saml#253]
Hello, I have been making some tests with the Flask_Demo and some IDPs but when I try to log in it appears an error of Stale Request. I have been told by some co-workers that its an issue that can be solved with the ClockSew configuration but I am not sure where I can specify this either in the settings.json or advanced_settings.json. I am trying to find something similar to accepted_time_diff from pysaml2

**Comment by pitbulk** [comment]
ALLOWED_CLOCK_DRIFT. It is defined at the [constants.py](https://github.com/SAML-Toolkits/python3-saml/blob/master/src/onelogin/saml2/constants.py#L20) file
