### ISSUE TITLE
Error validating acs response

### ISSUE THREAD

**Issue by jimstraus** [SAML-Toolkits/python3-saml#257]
I'm adding OneLogin authentication to a Django rest application.  In local development, things are working fine.  When I try to deploy into our kubernetes cluster, I get

```
Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{urn:oasis:names:tc:SAML:2.0:assertion}Issuer' does not resolve to a(n) element declaration.
```

When I decode the response, the issuer matches what is in the settings file.  I believe the OneLogin configuration that responds to localhost and to the cluster are generally the same (just the SP server name is different).

Is there something I'm missing?  Thanks!

**Comment by pitbulk** [comment]
Never saw that before, is your kubernete cluster reading properly the xsd files to validate the XML. 
Are the XML the same on local and kubernete (maybe a parse issue)?
