### ISSUE TITLE
parse() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by tahayk** [SAML-Toolkits/python3-saml#265]
I'm following your documentation using v1.10.1; 
when I try this code (with a valid idp-metadata-URL): 
`idp_data = OneLogin_Saml2_IdPMetadataParser.parse_remote('https://example.com/auth/saml2/idp/metadata', timeout=5)`

I get: 
```
File "c:\users\x\.virtualenvs\api-brigxtbz\lib\site-packages\onelogin\saml2\idp_metadata_parser.py", line 84, in parse_remote
    return cls.parse(idp_metadata, entity_id=entity_id, **kwargs)
TypeError: parse() got an unexpected keyword argument 'timeout'
```

**Comment by pitbulk** [comment]
What version of python3-saml are you using?

The error you see is that python3-saml does not recognize the timeout parameter provided.
Maybe in the version you are using, the support of timeout was not implemented.
