### ISSUE TITLE
Malformed XML results in a lxml.etree.XMLSyntaxError exception

### ISSUE THREAD

**Issue by kjwilcox** [SAML-Toolkits/python3-saml#27]
After creating a `OneLogin_Saml2_Auth` object with a request that contains malformed XML and calling `process_response()`, the call will raise a `lxml.etree.XMLSyntaxError` exception.

This is reasonable behavior, but I think it could be improved. I think that in general, libraries should try to avoid raising exceptions that their dependencies raise. There is already a `OneLogin_Saml2_Error` exception that is raised in various error cases. What would you think about catching `lxml.etree.Error` exceptions in `OneLogin_Saml2_XML` and raising a `OneLogin_Saml2_Error` exception with a new error code for XML parse failures?

**Comment by pitbulk** [comment]
I think makes sense. Do you want to collaborate with a PR with unit tests?

**Comment by kjwilcox** [comment]
Unfortunately, I don't have the available time to submit a PR for this right now. Sorry about that.

We have worked around this issue in our codebase for now by catching `lxml.etree.Error` exceptions.
