### ISSUE TITLE
ImportError undefined symbol: xmlSecCryptoAppKeysMngrCertLoad

### ISSUE THREAD

**Issue by duwenjun** [SAML-Toolkits/python3-saml#270]
ImportError: /data/wwwroot/powerdns-admin/flask/lib64/python3.6/site-packages/xmlsec.cpython-36m-x86_64-linux-gnu.so: undefined symbol: xmlSecCryptoAppKeysMngrCertLoad

any one know how to fix?

**Comment by pitbulk** [comment]
Maybe report this issue directly to the xmlsec library:
https://github.com/mehcode/python-xmlsec/issues
