### ISSUE TITLE
scn.find doensn't work on debina

### ISSUE THREAD

**Issue by mislavgrgic** [SAML-Toolkits/python3-saml#302]
So we are having a problem with scn.find method. On alpine, it works with no problem but on Debian for some reason returns None for every SAML. 
`scn.find('saml:SubjectConfirmationData', namespaces=OneLogin_Saml2_Constants.NSMAP)`

We had a similar problem on Alpine as well everything worked ok if we installed with pip 21.1.2 but if we would use a newer version of pip same thing would happen, scn.find would stop working. Can I get some suggestions on why this could happen?

**Comment by pitbulk** [comment]
Yes, it seems related to the version used on lxml and its dependency libxml2
