### ISSUE TITLE
get_session_expiration and get_last_assertion_not_on_or_after return None

### ISSUE THREAD

**Issue by shaozi** [SAML-Toolkits/python3-saml#322]
The methods `get_session_expiration` and `get_last_assertion_not_on_or_after` of `OneLogin_Saml2_Auth` returns `None` instead of the value in `NotOnOrAfter`:

```python
auth = OneLogin_Saml2_Auth(
        req,
        custom_base_path='config',
)
auth.process_response(request_id=request_id)
if auth.is_authenticated():
        print(auth.get_session_expiration())
        print(auth.get_last_assertion_not_on_or_after())
```

**Comment by kotofos** [comment]
You probably should check for errors first

```
        errors = auth.get_errors()
        if errors:
            error_reason = auth.get_last_error_reason()
            raise ValueError(f'{error_reason} {"".join(errors)}')
 ```

**Comment by pitbulk** [comment]
@shaozi , as @kotofos suggested, those attributes are only available if the SAML Response was valid, if you are directly using the OneLogin_Saml2_Auth object.

See [process_response](https://github.com/SAML-Toolkits/python3-saml/blob/master/src/onelogin/saml2/auth.py#L131)
