### ISSUE TITLE
Support newer version of Lxml for Python 3.11

### ISSUE THREAD

**Issue by rlaunch** [SAML-Toolkits/python3-saml#328]
Lxml vesions < 4.9.0 don't fail to install on Python 3.11. [https://bugs.launchpad.net/lxml/+bug/1969912](https://bugs.launchpad.net/lxml/+bug/1969912)

Currently python3-saml forces the lxml package version to < 4.7.1, which prevents the installation of python3-saml in Python 3.11 environments. I can confirm Lxml builds correctly in Python 3.11 environments when using 4.9.1, however the python3-saml install downgrades this then fails. Attempting to install in Python 3.10 environments works as expected.

**Comment by sreenivasulureddysura** [comment]
@rlaunch Any one is working on this issue? How to work around to this installation?

**Comment by sreenivasulureddysura** [comment]
May be windows installation failing for lxml that they restricted to 4.7.1 version.
https://github.com/streamlink/streamlink/issues/4903

**Comment by sreenivasulureddysura** [comment]
PR for lxml update: https://github.com/lxml/lxml/pull/356

**Comment by kleptog** [comment]
Near as I can tell it's being worked on, see #320, hopefully new release soon.

**Comment by pitbulk** [comment]
Next release will not restrict lxml.

**Comment by nolar** [comment]
@pitbulk Thanks for taking care of this library! Can you please hint when the next release will happen approximately?

**Comment by RossinesP** [comment]
I'd love to know too if there is an approximate release date ? Your package is neat, but it's the last one of our dependencies which is not compatible yet.
Is there anything we can do to help you ?

**Comment by pitbulk** [comment]
@RossinesP , @nolar 

On 27 Dec 2022 the 1.15 version was released.

See https://pypi.org/project/python3-saml/1.15.0/

**Comment by sreenivasulureddysura** [comment]
@pitbulk Still the issue exits
