### ISSUE TITLE
The most recent version depends on the vulnerable lxlm version

### ISSUE THREAD

**Issue by lexabug** [SAML-Toolkits/python3-saml#336]
The most recent version of the python3-saml (`v1.14.0`) depends on the vulnerable version of the **lxml** (`<4.7.1`, see [here](https://github.com/onelogin/python3-saml/blob/master/setup.py#L37)). The pyup.io [says](https://pyup.io/p/pypi/lxml/2ff/) that the only version of the **lxml** without know vulnerabilities is `v4.9.1`.
Are you planing to eliminate the vulnerable dependency?

**Comment by kleptog** [comment]
Hopefully a new release soon, see #320.

**Comment by lexabug** [comment]
@kleptog great news! Thx.

**Comment by pitbulk** [comment]
Hi, I'm trying to get time to put everything running, I will give priority to this new release

**Comment by pitbulk** [comment]
Next release will not restrict lxml
