### ISSUE TITLE
Merge settings.json and advanced_settings.json

### ISSUE THREAD

**Issue by colinet** [SAML-Toolkits/python3-saml#345]
It would make sense to merge the settings parameters of files : 
- settings.json
- advanced_settings.json

into a single file such as settings.json.

Just a cosmetic proposal.

**Comment by pitbulk** [comment]
In your project, you are able to use them unified.

It is just a cosmetic stuff, as you indicated, but unifying them right know have impact on old versions of the extension.

**Comment by colinet** [comment]
Indeed, the content of advanced_settings.json may be moved into settings.json.
And file advanced_settings.json may be removed. Good to know.
