### ISSUE TITLE
Documentation for running the project

### ISSUE THREAD

**Issue by mohak007** [SAML-Toolkits/python3-saml#346]
Hi, 

I am new to flask and django projects. But I am aware of the SAML2 and its flow. For a aspirant like me, I request the contributors if they can provide the documentation which includes how to execute/run the project will be handy.

**Comment by pitbulk** [comment]
Take a look on this demos:
- https://github.com/SAML-Toolkits/python3-saml/tree/master/demo-django
- https://github.com/SAML-Toolkits/python3-saml/tree/master/demo-flask

And documentation:
 - https://github.com/SAML-Toolkits/python3-saml#demo-django
 - https://github.com/SAML-Toolkits/python3-saml#demo-flask
