### ISSUE TITLE
Extract metadata file/URL with python3-saml

### ISSUE THREAD

**Issue by chiavariniluca** [SAML-Toolkits/python3-saml#351]
I have a Python-Django project and I'm trying to integrate with a C#/.NET existing website SAML authentication, using their idp.
I absolutely need to generate a metadata file to give to whoever manages the IdP (C#/.NET website) to implement SSO.
How can I implement it?

**Comment by pitbulk** [comment]
The [Django Demo](https://github.com/SAML-Toolkits/python3-saml/blob/master/demo-django/demo/views.py#L131) contains a metadata method that contains an example on how generate the XML file

Here you have another example:
https://github.com/SAML-Toolkits/python3-saml#the-sp-endpoints
