### ISSUE TITLE
Django support

### ISSUE THREAD

**Issue by eljeffeg** [SAML-Toolkits/python3-saml#355]
Trying to understand the progression from OneLogin library to SAML-Toolkits.  I noticed that there is a django demo folder.  Does this mean that using something like https://github.com/penn-state-dance-marathon/python3-saml-django (which says it's a wrapper for the OneLogin library) is unnecessary and we should just use python3-saml directly?

**Comment by eljeffeg** [comment]
Following up on this as no one responded and I'm trying to implement.  I'm trying to add SAML to a django application that is using `include('django.contrib.auth.urls'))`.  So for example, will `@login_require` still work?  I'd like to include SAML as seamlessly as possible.

**Comment by pitbulk** [comment]
HI @eljeffeg, sorry for the delayed reply.

[python3-saml-django](https://github.com/penn-state-dance-marathon/python3-saml-django) uses python3-saml and I believe is a solution that will have more features/improvements if you compare it with the solution provided in the django-demo.

@login_require is a decorator that will force not authenticated user to be redirected to the login page.
Not sure how currently your login controlled is managed, but in such login page you have 2 options:
- Offer a SAML link that should initiate the SAML SSO flow.
- If you want to force all users to use SAML SSO, then you can directly redirect the user to the endpoint that initiates the SAML SSO in your app.
