### ISSUE TITLE
Support for Python3.11

### ISSUE THREAD

**Issue by mariya-interra** [SAML-Toolkits/python3-saml#356]
I am not able to install dependencies of this package on Python 3.11.

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for xmlsec
Failed to build xmlsec
ERROR: Could not build wheels for xmlsec, which is required to install pyproject.toml-based projects

However, python3-saml package can successfully be installed on Python 3.8. 
Is there any plan to support Python 3.11 ?

**Comment by Danxx26hub** [comment]
not just 3.11 but seems to be anything higher than 3.8:

pip 22.0.2 from /home/danielgalvan/PythonProjects/Onelogin/env/lib/python3.10/site-packages/pip (python 3.10)
(saml) danielgalvan@ubnt22:~/PythonProjects/Onelogin$ python --version
Python 3.10.6
(saml) danielgalvan@ubnt22:~/PythonProjects/Onelogin$ pip install python3-saml
Collecting python3-saml
  Using cached python3_saml-1.15.0-py3-none-any.whl (76 kB)
Collecting xmlsec>=1.3.9
  Using cached xmlsec-1.3.13.tar.gz (64 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting isodate>=0.6.1
  Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Requirement already satisfied: lxml!=4.7.0,>=4.6.5 in ./env/lib/python3.10/site-packages (from python3-saml) (4.9.2)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for xmlsec (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/xmlsec
      copying src/xmlsec/py.typed -> build/lib.linux-x86_64-cpython-310/xmlsec
      copying src/xmlsec/__init__.pyi -> build/lib.linux-x86_64-cpython-310/xmlsec
      copying src/xmlsec/constants.pyi -> build/lib.linux-x86_64-cpython-310/xmlsec
      copying src/xmlsec/tree.pyi -> build/lib.linux-x86_64-cpython-310/xmlsec
      copying src/xmlsec/template.pyi -> build/lib.linux-x86_64-cpython-310/xmlsec
      running build_ext
      error: Unable to invoke pkg-config.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xmlsec
Failed to build xmlsec
ERROR: Could not build wheels for xmlsec, which is required to install pyproject.toml-based projects
(saml) danielgalvan@ubnt22:~/PythonProjects/Onelogin$

**Comment by davetrollope** [comment]
I ran in to this trying to install python3-saml on an m1 mac recently using python 3.8. I believe the issue lies in the xmlsec project, not python3-saml. You might want to reach out to that project to understand its dependencies.

**Comment by pitbulk** [comment]
As @davetrollope commented, python3-saml depends on https://github.com/xmlsec/python-xmlsec, we waiting for a resolution there.

These issues and PRs are relevant:
- https://github.com/xmlsec/python-xmlsec/pull/253
- https://github.com/xmlsec/python-xmlsec/pull/253
- https://github.com/xmlsec/python-xmlsec/pull/251

**Comment by mariya-interra** [comment]
Thanks for the response. I'll follow the respective tickets of xmlsec library.

**Comment by eljeffeg** [comment]
Is there an alternative to using xmlsec for this project?  They seem fairly non-responsive in addressing the issue.

**Comment by eljeffeg** [comment]
I wanted to follow up on this.. I know it's not your issue, but perhaps you can reach out to the xmlsec team and get some movement.  The PR is already there, they just have to merge it in and push to pypi.  I have a new SAML implementation for a project and I'm going to have to recommend the team use [pythonsaml2](https://github.com/IdentityPython/pysaml2) if we can't get them to update their library, which causes issues updating containers to the latest patched versions.  I do really appreciate your software and efforts. 🙏

**Comment by eljeffeg** [comment]
Possible replacement for python-xmlsec. https://github.com/XML-Security/signxml

**Comment by kennedymeadows** [comment]
Hey did this ever get resolved? I'm running into this issue trying to use `python3-saml`

**Comment by CyDefender** [comment]
Just waiting on https://github.com/xmlsec/python-xmlsec to push a new release to pypy, but they've made the updates.

**Comment by pitbulk** [comment]
There is now available xmlsec versions compatible with the latest, so closing this.

**Comment by mariya-interra** [comment]
Thanks @pitbulk.
