### ISSUE TITLE
Deprecated signature algorithm found: http://www.w3.org/2000/09/xmldsig#rsa-sha1

### ISSUE THREAD

**Issue by aralyekta** [SAML-Toolkits/python3-saml#361]
Hi, I'm new to using SAML with django and I was following the tutorial at https://developers.onelogin.com/saml/python. Last friday, I was able to set it up and login through onelogin to the demo django app. However, 4 days later, I started getting 
```
invalid_response
Reason: Deprecated signature algorithm found: http://www.w3.org/2000/09/xmldsig#rsa-sha1
``` 
errors while trying to authenticate to onelogin from the same app. To check again, I set up another app from the same tutorial and I still get the same error. The webpage looks like below:
<img width="1155" alt="Screenshot 2023-06-20 at 12 38 17" src="https://github.com/SAML-Toolkits/python-saml/assets/44121565/fba171e9-fd58-4109-8845-743a79871cdb">
What could be the reason?

**Comment by pitbulk** [comment]
At the IdP, you can define how the SAMLResponses gonna be signed, select a non deprecated algorithm.
(SAML Signature Algorithm field)

**Comment by fredcy** [comment]
Perhaps the docs at https://developers.onelogin.com/saml/python should talk about this. Changing from the default of SHA-1 to SHA-256 for 'SAML Signature Algorithm' on the SSO tab of the app at onelogin.com makes this error go away.
