### ISSUE TITLE
onelogin 3.1.6 depends on python-dateutil~=2.7.0

### ISSUE THREAD

**Issue by stevewoolley** [SAML-Toolkits/python3-saml#368]
python-dateutil is now at version 2.8+ and a number of python libraries are now specifying >=2.8
Please update onelogin to support python-dateutil >= 2.7 rather than ~= 2.7

**Comment by pitbulk** [comment]
@stevewoolley, can you share where are we forcing python-dateutil ~= 2.7 ?
