### ISSUE TITLE
Question about release process

### ISSUE THREAD

**Issue by galynazholtkevych** [SAML-Toolkits/python3-saml#369]
Hello! Recently you just merged my contribution [pr](https://github.com/SAML-Toolkits/python3-saml/pull/366) 

May I know, when this change will be published to pypi, so we can update the lib?

Thanks!

**Comment by pitbulk** [comment]
@galynazholtkevych new releases are generated when relevant features/hot-fixes were added to the project.

I plan to do a new release at the end of the month.

**Comment by galynazholtkevych** [comment]
@pitbulk cool, looking forward to it! Thanks

**Comment by galynazholtkevych** [comment]
Hey, are there any updates?
