### ISSUE TITLE
SAML Response not found, Only supported HTTP_POST Binding

### ISSUE THREAD

**Issue by jmartin111** [SAML-Toolkits/python3-saml#383]
Proposed Labels: [help wanted, question] 

I am wondering if this is just a simple misconfiguration on my part. This is definitely my first SSO rodeo so I am just looking for some generic advice based on the data I supply below.

Specifically the exception I am hitting in onelogin's lib is here:

  File "/opt/bitnami/python/lib/python3.10/site-packages/onelogin/saml2/auth.py", line 139, in process_response
    raise OneLogin_Saml2_Error(
onelogin.saml2.errors.OneLogin_Saml2_Error: SAML Response not found, Only supported HTTP_POST Binding

This is decoded SAML response from our (internal) IdP:

<samlp:Response Version="2.0" ID="Redacted" IssueInstant="2023-10-13T18:32:14.503Z" InResponseTo="ONELOGIN_Redacted" Destination="https://service.com/saml"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">Redacted.UAT.SAML2.0</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference URI="Redacted">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>Redacted</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>Redacted</ds:SignatureValue>
    </ds:Signature>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester"/>
        <samlp:StatusMessage>ProtocolBinding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect disallowed for transport of SSO response.</samlp:StatusMessage>
    </samlp:Status>
</samlp:Response>

And here is my IdP configuration; as you can see, the IdP binding is set to HTTP-POST:

{
    "strict": True,
    "debug": True,
    "idp": {
        "entityId": "Redacted.UAT.SAML2.0",
        "singleSignOnService": {
            "url": "https://pf-uat.us.com/idp/SSO.saml2",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
        "x509cert": "Redacted"
    },
    "sp": {
        "entityId": "https://service.com",
        "assertionConsumerService": {
            "url": "https://service.com/saml",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        }
    },
    "security": {
        "wantAttributeStatement": False
    }
}

**Comment by pitbulk** [comment]
The error "SAML Response not found, Only supported HTTP_POST Binding" is raised when no SAMLResponse is sent at the POST of the request.

Maybe the IdP sent the SAMLResponse via HTTP_Redirect or maybe you directly accessed the ACS endpoint.
