### ISSUE TITLE
Callback stuck on auth.process_response

### ISSUE THREAD

**Issue by NeuraByte-UCSD-ITS** [SAML-Toolkits/python3-saml#396]
backend: Fast API
frontEnd: Next.js
python3-saml version 1.15.0

Hi, I am using python3-saml for SSO implementation in my project which successfully takes me to the login page, Once I enter my credentials press login button it triggers callback function which gets stuck on this line "auth.process_response"

<img width="793" alt="image" src="https://github.com/SAML-Toolkits/python3-saml/assets/122659492/a6a1deae-98ee-4ea7-b9ff-dd7a65cbd730">

<img width="719" alt="image" src="https://github.com/SAML-Toolkits/python3-saml/assets/122659492/e675ac26-3318-44f5-83ee-c1a468079ae4">

<img width="736" alt="image" src="https://github.com/SAML-Toolkits/python3-saml/assets/122659492/d70e3007-66d8-40d4-9051-4cc107d76c27">

<img width="831" alt="image" src="https://github.com/SAML-Toolkits/python3-saml/assets/122659492/2cdfdad8-3df5-4190-b0d2-e8b8f04b6c0c">

**Comment by jshelley** [comment]
I am having this same issue.

**Comment by pitbulk** [comment]
Can you add a debugger and see where inside the process_response got stuck?

**Comment by NeuraByte-UCSD-ITS** [comment]
Hi, I was able to get that issue resolved by downgrading the lbxml library from version lxml==5.1.0 to lxml==4.9.4. However, now I have another issue. When I try to get attributes I am unable to get email, can this be configured in settings.json, advanced_settings.jscon or in saml.py? 

<img width="886" alt="image" src="https://github.com/SAML-Toolkits/python3-saml/assets/122659492/853309b4-e14c-4c9e-b3f4-44ee1d13eda7">
---
<img width="1112" alt="image" src="https://github.com/SAML-Toolkits/python3-saml/assets/122659492/8c7cab9d-5c91-4b44-9793-c69419ba7083">

**Comment by pitbulk** [comment]
>  I was able to get that issue resolved by downgrading the lbxml library from version lxml==5.1.0 to lxml==4.9.4

Have you tried to install the lxml library as follows:
```
pip install --force-reinstall --no-binary lxml lxml
```

> When I try to get attributes I am unable to get email

It seems the IdP is providing username, eduPersonScopedAffiliation, firstname, lastname, fullname but not the email.
You will need to contant the IdP administrator and ask them to release the email info in the SAMLResponse.

**Comment by lovelydett** [comment]
`lxml==4.9.3` works, thx for saving my day.

**Comment by smaccona** [comment]
I had this issue with a Django 4.2 app. I can confirm that installing lxml via `pip install --force-reinstall --no-binary lxml lxml` seems to have fixed it. @pitbulk do you have any insight into why the binary package for `lxml` doesn't work? We prefer to use binaries in our build pipeline when possible.

I can also confirm that downgrading to `lxml==4.9.4` also worked for us. That's what we're using in our build at the moment.

**Comment by pitbulk** [comment]
@smaccona if you search in the [Issues section](https://github.com/SAML-Toolkits/python3-saml/issues) there were tons of issues recently with the lxml version for different reasons.

The main issue was due to incompatibilities with libxml2.

@NeuraByte-UCSD-ITS , you should not be using async calls for the SAML handshake.
