### ISSUE TITLE
Error with Passenger

### ISSUE THREAD

**Issue by CymeriaHub** [SAML-Toolkits/python3-saml#406]
Dear ,

when running on apache passenger my flask website, i am able to generate the url to access to the IDP thanks to auth.login() (auth coming from OneLogin_Saml2_Auth ) and redirect the user to the  generate url. But after that all the session are destroy for all users and nobody is able to connect (before i restart the server)

Did you already experiment such behavior?

lxml==5.2.1
xmlsec==1.3.14
python3-saml==1.16.0

**Comment by CymeriaHub** [comment]
thanks for all

**Comment by pitbulk** [comment]
Sorry for the delayed reply. 

With the provided information I'm not able to determine what was wrong with your SAML integration.

Is not normal that a login process kill all the sessions of your app.
