### ISSUE TITLE
Single Logout Service never called

### ISSUE THREAD

**Issue by nhill-cpi** [SAML-Toolkits/python3-saml#85]
Hi,

When I log out of my Django application that is a service provider, I am correctly redirected to the logout page of the IDP that I am using (Salesforce in this case). However, when I then navigate back to my site (i.e. the service provider), I am not presented with the login page, but instead it seems like I'm already logged in. I then figured out that my singleLogoutService url is never being hit, and so auth.process_slo() is never being executed (so my session is not being deleted). Do you know what could be causing this?

Thanks.

**Comment by pitbulk** [comment]
Install the [SAMLTracer](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/) tool and review the SLO trace.

When you log out from Django, a LogoutRequest should be sent to Salesforce and then it should reply a LogoutResponse back and after process it django session is closed.
I assume that Salesforce never replies you the LogoutResponse, so Django session is not closed.

**Comment by hillrnate** [comment]
I can confirm that Salesforce never replies back with the LogoutResponse.

**Comment by rlancejohnson** [comment]
Were you guys ever able to figure this out? I am experiencing the same issue.
